apiVersion: v1
entries:
  kube-janitor:
  - apiVersion: v1
    appVersion: v20.4.1
    created: "2020-01-07T13:31:04.993386765+01:00"
    description: Clean up (delete) Kubernetes resources after a configured TTL (time
      to live)
    digest: e2a0eeafb37b688d4a3d8b4f56268abf55edce6ffd36e87b957d64acb5fd5d27
    home: https://github.com/hjacobs/kube-janitor
    maintainers:
    - email: henning@jacobs1.de
      name: hjacobs
    - email: me@mayppong.com
      name: mayppong
    name: kube-janitor
    sources:
    - https://github.com/hjacobs/kube-janitor
    urls:
    - kube-janitor-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    appVersion: v20.4.1
    created: "2020-01-07T13:31:04.993386765+01:00"
    description: Clean up (delete) Kubernetes resources after a configured TTL (time
      to live)
    digest: e2a0eeafb37b688d4a3d8b4f56268abf55edce6ffd36e87b957d64acb5fd5d27
    home: https://github.com/hjacobs/kube-janitor
    maintainers:
    - email: henning@jacobs1.de
      name: hjacobs
    - email: me@mayppong.com
      name: mayppong
    name: kube-janitor
    sources:
    - https://github.com/hjacobs/kube-janitor
    urls:
    - kube-janitor-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: 23.7.0
    created: "2023-11-27T13:52:09.57385+13:00"
    description: Clean up (delete) Kubernetes resources after a configured TTL (time
      to live)
    digest: 7a99dd993546e603d30d005bf4423d267718a87fb93a3589f871905424c26f60
    home: https://codeberg.org/hjacobs/kube-janitor
    maintainers:
    - email: henning@jacobs1.de
      name: hjacobs
    - email: me@mayppong.com
      name: mayppong
    name: kube-janitor
    sources:
    - https://codeberg.org/hjacobs/kube-janitor
    urls:
    - kube-janitor-0.3.1.tgz
    version: 0.3.1
generated: "2020-01-07T13:31:04.992860036+01:00"
